"""listing and campaign suspension

Revision ID: 506a44f61f0d
Revises: e8e07d3ef1d1
Create Date: 2026-07-28 20:51:30.603904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506a44f61f0d'
down_revision: Union[str, Sequence[str], None] = 'e8e07d3ef1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(), nullable=True))

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('suspended_at')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('suspended_at')

    # ### end Alembic commands ###
