"""platform_media link_url + cover

Revision ID: 9aafcebe61ab
Revises: 36547a27dfc4
Create Date: 2026-07-26 17:31:14.157228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aafcebe61ab'
down_revision: Union[str, Sequence[str], None] = '36547a27dfc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cover_content_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_media', schema=None) as batch_op:
        batch_op.drop_column('cover_content_type')
        batch_op.drop_column('cover_path')
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
