"""deal views promised/delivered

Revision ID: c66aec75bdc5
Revises: dfdde640b409
Create Date: 2026-07-28 10:51:41.716866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66aec75bdc5'
down_revision: Union[str, Sequence[str], None] = 'dfdde640b409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views_promised', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views_delivered', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('views_delivered')
        batch_op.drop_column('views_promised')

    # ### end Alembic commands ###
