"""profile media, listing/campaign images, support tickets

Revision ID: c8ac492952be
Revises: 9aafcebe61ab
Create Date: 2026-07-27 11:30:00.427946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ac492952be'
down_revision: Union[str, Sequence[str], None] = '9aafcebe61ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_content_type', sa.String(), nullable=True))

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image_content_type', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('avatar_content_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('intro_video_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('intro_video_content_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('intro_video_content_type')
        batch_op.drop_column('intro_video_path')
        batch_op.drop_column('avatar_content_type')
        batch_op.drop_column('avatar_path')

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('image_content_type')
        batch_op.drop_column('image_path')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('image_content_type')
        batch_op.drop_column('image_path')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))

    op.drop_table('support_tickets')
    # ### end Alembic commands ###
