"""roles, admin audit log, mfa, suspension

Revision ID: e8e07d3ef1d1
Revises: c66aec75bdc5
Create Date: 2026-07-28 16:08:05.165895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e07d3ef1d1'
down_revision: Union[str, Sequence[str], None] = 'c66aec75bdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audit_log_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so the NOT NULL columns can be added to existing rows.
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False,
                                      server_default='USER'))
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('banned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('mfa_recovery_codes', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ------------------------------------------------------------------
    # Make the audit log immutable AT THE DATABASE LEVEL. Append-only: any
    # UPDATE or DELETE is rejected by the engine itself, so the history cannot
    # be rewritten through the ORM, the API, or a direct SQL console — by an
    # admin, a regular user, or anyone else.
    # ------------------------------------------------------------------
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("""
            CREATE OR REPLACE FUNCTION promoslot_audit_log_immutable()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'admin_audit_log is append-only: % is not permitted',
                                TG_OP;
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER admin_audit_log_no_update
            BEFORE UPDATE ON admin_audit_log
            FOR EACH ROW EXECUTE FUNCTION promoslot_audit_log_immutable();
        """)
        op.execute("""
            CREATE TRIGGER admin_audit_log_no_delete
            BEFORE DELETE ON admin_audit_log
            FOR EACH ROW EXECUTE FUNCTION promoslot_audit_log_immutable();
        """)
    elif bind.dialect.name == "sqlite":
        op.execute("""
            CREATE TRIGGER admin_audit_log_no_update
            BEFORE UPDATE ON admin_audit_log
            BEGIN
                SELECT RAISE(ABORT, 'admin_audit_log is append-only: UPDATE is not permitted');
            END;
        """)
        op.execute("""
            CREATE TRIGGER admin_audit_log_no_delete
            BEFORE DELETE ON admin_audit_log
            BEGIN
                SELECT RAISE(ABORT, 'admin_audit_log is append-only: DELETE is not permitted');
            END;
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS admin_audit_log_no_update ON admin_audit_log;")
        op.execute("DROP TRIGGER IF EXISTS admin_audit_log_no_delete ON admin_audit_log;")
        op.execute("DROP FUNCTION IF EXISTS promoslot_audit_log_immutable();")
    elif bind.dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS admin_audit_log_no_update;")
        op.execute("DROP TRIGGER IF EXISTS admin_audit_log_no_delete;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_column('mfa_recovery_codes')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('banned_at')
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('role')

    with op.batch_alter_table('admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audit_log_action'))

    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
